[template]
name = "template_with_window"
description = "Template Rust avec fenêtre (winit + pixels, etc.)"

#[run_config]
#name = "Run"
#type = "CargoCommandRunConfiguration"
#build_profile = "dev"
#command = "run"
#working_directory = "$PROJECT_DIR$"
#emulate_terminal = true
#channel = "DEFAULT"
#required_features = true
#all_features = false
#with_sudo = false
#build_target = "REMOTE"
#backtrace = "SHORT"
#is_redirect_input = false
#redirect_input_path = ""

#[compile_to_linux]
#name = "Compile_to_linux"
#type = "ShConfigurationType"
#script_path = "$PROJECT_DIR$/Script/Compile_To_Linux.ps1"
#interpreter_path = "$PROJECT_DIR$/../../../../../../../WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe"
#execute_in_terminal = true
#execute_script_file = true

#[github_creation]
#name = "Github_Creation"
#type = "ShConfigurationType"
#script_path = "$PROJECT_DIR$/Script/Connect_GitHub.sh"
#interpreter_path = "$PROJECT_DIR$/../../../../../../../WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe"
#execute_in_terminal = true
#execute_script_file = true
